### ISSUE TITLE
Feature Suggestion - Placing Nodes in Special Formspec Sets Auto-Trash Function

### ISSUE THREAD

**Issue by LazyJ** [minetest-mods/unified_inventory#100]
While reading a minetest-project archive I came across a discussion about adding ways to automatically delete unwanted items from the inventory. Some suggestions where to have the overflow from the main inventory redirected into bags. Another was a trash icon at the end of each row so the player could bulk delete the row's contents.

My suggestion is to squeeze in another formspec page, like the bags page, where the entire page is filled with empty slots. Whatever is placed in a slot will automatically be deleted from the inventory when the player digs it in the world. The player will first have to either pull a sample node from one of the inventory pages or dig a sample node _(this would cover things not shown in creative inventory like nodes made from MoreBlock's circular saw)_ and then the player would have to move that node from their inventory to the auto-trash page. This way the player has to make a deliberate decision as to which specific items to be auto-trashed - no accidental deleting of wanted nodes by clicking on the wrong trash icon _(I've done that too many times in creative-mode; bumbling trigger-finger wiping out my entire setup in inventory)_.

My coding skills are not up to task so I am unable to provide a PR on this one.

**Comment by numberZero** [comment]
Sounds reasonable.

> My coding skills are not up to task

That’s sad.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/unified_inventory/issues
