### ISSUE TITLE
Unclear licenses and copyright

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/unified_inventory#103]
Hi,

I was pondering packaing unified_inventory for Debian, but for that I need to know what license applies to each file. In particular, for textures/images, I have a statement in README.md, then a image_credits.txt which allowed me to track the licenses, but nothing for sounds.

Speaking of which, I don't know what is the status of a LGPL-2.1+ program using a GPL-2+ file.

I'm attaching my work-in-progress debian/copyright so you see what I found (renamed a copyright.txt because github was unhappy): [copyright.txt](https://github.com/minetest-technic/unified_inventory/files/1267418/copyright.txt)

Snark on #debian-games

**Comment by SnarkBoojum** [comment]
And locale/* ?

**Comment by SnarkBoojum** [comment]
Is the project dead?

**Comment by numberZero** [comment]
Almost. Some people make PRs (to `technic` itself), some review them, but no one merges them.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/unified_inventory/issues
