### ISSUE TITLE
Add sorting inventory function

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/unified_inventory#106]
Pretty often your inventory is mess, sorting it via button or hotkey would be nice, it should sort inventory part separately from hudbar to not mess up your tools.
![default](https://user-images.githubusercontent.com/16494741/33799813-e0591d1a-dd3b-11e7-8a7a-853cfdf01232.png)

**Comment by aerozoic** [comment]
What kind of sorting, how would it sort? Can you give an example?  Also the hotbar size is customizable so it would need to check for that.
:large_orange_diamond:

**Comment by Fixer-007** [comment]
>What kind of sorting, how would it sort?

The simplest way is to sort by node name.

**Comment by DS-Minetest** [comment]
Something like `technic_chest`'s `sort_inventory` function could be used (not the one in master that clears item meta, but the one from https://github.com/minetest-mods/technic/pull/389).

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/unified_inventory/issues
