### ISSUE TITLE
Remove background or use formspec theming

### ISSUE THREAD

**Issue by rubenwardy** [minetest-mods/unified_inventory#113]
You should either:

* Remove the special UI background (recommended x1000)
* or use formspec theming so it appears on all formspecs by default: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4116
* Use a special UI background which matches MTG's default more

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/unified_inventory/issues

**Comment by rusty-snake** [comment]
Is this really moved? Here are still commits, and your link is either a private-repo or 404.

**Comment by isaiah658** [comment]
Since this was opened again, does that mean if a pull request was submitted changing it to use the theming provided by the default mod that it would be merged?

**Comment by SmallJoker** [comment]
I wouldn't oppose that as long it looks good. Though there might be mods that add custom u_i backgrounds which would then be inconsistent with the new design.

**Comment by SmallJoker** [comment]
Done
