### ISSUE TITLE
Sound licensing isn't listed

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/unified_inventory#121]
I'm interested in reusing some of the sounds in this mod, but the license listing in readme.md doesn't include those. What license are they under?

**Comment by HybridDog** [comment]
According to the README.md, everything not listed is CC-BY-4.0:
#
RealBadAngel: (CC-BY-4.0)
  * Everything else.
#
This does of course not sound reliable.
I found some of the sounds at freesound.org and in the minetest ambience mod, e.g.:
dingdong (with longer reverberation): https://freesound.org/people/bennstir/sounds/81072/
bird: https://github.com/Neuromancer56/MinetestAmbience/blob/master/ambience/sounds/Best%20Cardinal%20Bird.ogg

**Comment by SmallJoker** [comment]
Documented.
