### ISSUE TITLE
Dyeing and dyed items completely broken v5

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/unified_inventory#124]
Hi,

My servers running v5 stable have a strange problem, but I don't know what mod is responsible. After speaking to VanessaE on IRC, she suggested unified_inventory might be to blame.

https://forum.minetest.net/viewtopic.php?f=6&t=22344&p=346047

* Punching clay and wood with dye does nothing but attempt to pick it up with the dye.

* Doing it the old way works, but pressing "All" in unified_inventory changes it to an undyeable wood/clay. Selecting one by one, however, works as expected.

There are no logs when attempting to punch clay or wood (now called apple wood) with dyes, which no longer works.

Here is the log from when picking up "Colored wooden planks" one by one from unified_inventory after mixing the old way:

> 2019-03-13 21:11:28: ACTION[Server]: player redblade7_owner crafts coloredwood:wood_block 1 0 "\u0001palette_index\u0002255\u0003"
>2019-03-13 21:11:28: ACTION[Server]: player redblade7_owner crafts coloredwood:wood_block 1 0 "\u0001palette_index\u0002255\u0003"
>2019-03-13 21:11:29: ACTION[Server]: player redblade7_owner crafts coloredwood:wood_block 1 0 "\u0001palette_index\u0002255\u0003"
>2019-03-13 21:11:29: ACTION[Server]: player redblade7_owner crafts coloredwood:wood_block 1 0 "\u0001palette_index\u0002255\u0003"
>2019-03-13 21:11:29: ACTION[Server]: player redblade7_owner crafts coloredwood:wood_block 1 0 "\u0001palette_index\u0002255\u0003"
>2019-03-13 21:11:29: ACTION[Server]: player redblade7_owner crafts coloredwood:wood_block 1 0 "\u0001palette_index\u0002255\u0003"

After pressing the "All" button, which creates an undyeable, white wood block also called "Colored wooden planks", the following shows up in logs:

>2019-03-13 21:13:07: ACTION[Server]: redblade7_owner crafts coloredwood:wood_block 93

If this is the wrong place to report it, please let me know.

**Comment by VanessaE** [comment]
> Punching clay and wood with dye does nothing but attempt to pick it up with the dye.

This hasn't been a thing for a few months now.  Unified Dyes uses an airbrush tool for this purpose now.

**Comment by redblade7** [comment]
OK, I was unaware of the airbrush, thank you.

However, @TooDumbForAName pointed out that coloredwoods' blank white fence overrides the crafting of apple wood fences in unified_inventory now. The airbrush does not have a brown that matches the apple wood exactly. Perhaps this bug should be filed with coloredwoods instead of unified_inventory?

**Comment by VanessaE** [comment]
I've noticed that also, but I doubt it's a bug in coloredwood or unified_dyes -- coloredwood only makes *default* wood fences, in various colors, by crafting them with a dye.  It does not mess around with apple wood at all (In fact, there's no mention of "apple" in either mod).

**Comment by redblade7** [comment]
Default wood has been changed to "apple wood" in v5

**Comment by VanessaE** [comment]
Well that explains the "apple" part :smiley:

Still, coloredwood doesn't alter the original craft.

**Comment by SmallJoker** [comment]
Will need to investigate further but what I can tell from now is that crafting and `InvRef:add_item` do not create the same ItemStacks. Apparently the metadata is not set for latter, resulting in two different items.
@redblade7 Would you please be so nice and create a dummy world to "bisect" the bad mod? The `All` button could be replaced with `/giveme`, with the same result.

**Comment by redblade7** [comment]
> 
> 
> Will need to investigate further but what I can tell from now is that crafting and `InvRef:add_item` do not create the same ItemStacks. Apparently the metadata is not set for latter, resulting in two different items.
> @redblade7 Would you please be so nice and create a dummy world to "bisect" the bad mod? The `All` button could be replaced with `/giveme`, with the same result.

I really don't understand what any of this means, can you please explain?

**Comment by SmallJoker** [comment]
@redblade7 
>  After speaking to VanessaE on IRC, she suggested unified_inventory might be to blame.

So if you disable unified_inventory and use `/giveme` instead - do you get the same issue? If so, then it's not an issue of unified_inventory.

**Comment by redblade7** [comment]
What item should I try a /giveme with?

Sorry, but I forgot all about this bug.

**Comment by SmallJoker** [comment]
Closed. Please request to re-open if there are steps to reproduce and where u_i is to blame.
