### ISSUE TITLE
Waypoints API 

### ISSUE THREAD

**Issue by int-ua** [minetest-mods/unified_inventory#133]
Reading [the code](https://github.com/minetest-mods/unified_inventory/blob/04b1cb9e7d748b4a2366ce321ac5a9f76e250a57/waypoints.lua#L175), do I understand correctly that it's currently impossible to add player waypoint from Lua code? It would be useful for showing last death location.

**Comment by SmallJoker** [comment]
Not in unified_inventory, but you can add waypoints by depending on `datastorage` in your mod:
`local waypoints = datastorage.get(player_name, "waypoints")`

But then there's no sane way to tigger the local function `update_hud()`.. If you need this feature, please propose a PR.
