### ISSUE TITLE
Improvements: Clear Grid button & click drag & gather all of a kind by double clicking.

### ISSUE THREAD

**Issue by sayore** [minetest-mods/unified_inventory#138]
Well, it is pretty time consuming clicking each field everytime, i really miss these features from MC.

Clear Grid Button

- Clears the whole grid and puts the Items into the inventory.

Click drag

- Drag an item across the grid, the items are put into each slot that has been dragged over equally.

Gather all of a kind via double clicking

- When double clicking for example a specific kind of wood, everything is getting accumulated into the mouse Stack up to the maximum of 99(/a stack).

I dont know if this is something to be implemented into the main game or into this mod. Im just putting this here as a feature request for the time being.

**Comment by DS-Minetest** [comment]
A clear grid button can be implemented in lua, the other features can't.

>Click drag

This is already possible.

**Comment by edenprojectde** [comment]
Click drag ist only possible with a single Item being put into the field. Its not able to click drag to divide the stack into the target slots.

**Comment by edenprojectde** [comment]
Is it not possible to iterate over the inventory to accumulate the kind of block/item beind double clicked?
It should be if there is at least an api gor click events

**Comment by DS-Minetest** [comment]
> Is it not possible to iterate over the inventory to accumulate the kind of block/item beind double clicked?
> It should be if there is at least an api gor click events

There isn't.
The client only sends item movements to the server, no grabs. (It only looks as if the item is attached to your cursor, the item actually remains in the slot where you got it from until you drop it.)

**Comment by OgelGames** [comment]
Looks like this could be closed? There is a clear-craft button added by `unified_inventory_plus`, and the other suggestions were added to the engine in https://github.com/minetest/minetest/pull/13146.
