### ISSUE TITLE
Item damage get's zero'ed on sorting in creator

### ISSUE THREAD

**Issue by norpol** [minetest-mods/unified_inventory#145]
If you put a single item (such as a axe) into the creator and then hit one of the sorting buttons, the item will lose it's damage information and be fully functional again. Same happens to things that are battery powered, but in this case the battery becomes empty. Sorry if I'm not using the correct terminology, I hope this is enough information for reproducing the bug.

**Comment by SmallJoker** [comment]
@andrenete

**Comment by andrenete** [comment]
Hello! I can't reproduce this issue when using 'Craft 1, 10, ALL' buttons with some tool on the crafting grid.

However, I can confirm there is an issue in [unified_inventory_plus](https://github.com/bousket/unified_inventory_plus) mod with its sorting buttons above the crafting grid. I believe that's what you're talking about.

![Screenshot_20200227_223953](https://user-images.githubusercontent.com/22382143/75480331-251e1280-59b2-11ea-8a13-5b84023e069d.png)

**Comment by norpol** [comment]
Ah sorry, I accidentally created the issue at the wrong repository!
