### ISSUE TITLE
Permanent Creative Mode

### ISSUE THREAD

**Issue by Lapis-Wolf** [minetest-mods/unified_inventory#163]
If i wished to play a purely survival session, I would disable creative mode and enable survival, however when I have unified inventory enabled, it would be like if I had never disabled creative mode. It would allow me to grab infinite resources and hold on to limited amounts of blocks like if I was never in survival mode. This takes the fun out of playing in survival mode. Can this possibly be fixed so I cannot grab infinite resources with creative mode disabled?

**Comment by SmallJoker** [comment]
Unified Inventory checks your privileges to enable per-user creative mode (e.g. for server admins)
Revoke the priv as follows: `/revokeme creative`

**Comment by Lapis-Wolf** [comment]
> Unified Inventory checks your privileges to enable per-user creative mode (e.g. for server admins)
> Revoke the priv as follows: `/revokeme creative`

Ok,thank you for the advice.

**Comment by SmallJoker** [comment]
I assume the issue is solved now. Closing.
