### ISSUE TITLE
After update, the bags are gone?

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/unified_inventory#167]
I updated from the last content db release to the current one on a 5.3.0 server.

All players lost their bags (but not their content). So if you drag a new bag onto the inventory slot, the bag shows the pre-update content.

In the database, there is now an additional entry in player_inventories per bag.

That's after the update:

```
player | inv_id | inv_width | inv_name | inv_size
-- | -- | -- | -- | --
User123 | 0 | 0 | main | 32
User123 | 1 | 0 | craft | 9
User123 | 2 | 0 | craftpreview | 1
User123 | 3 | 0 | craftresult | 1
User123 | 4 | 0 | bag1 | 1
User123 | 5 | 0 | bag2 | 1
User123 | 6 | 0 | bag3 | 1
User123 | 7 | 0 | bag4 | 1
User123 | 8 | 0 | bag1contents | 24
User123 | 9 | 0 | bag2contents | 24
User123 | 10 | 0 | bag3contents | 24
User123 | 11 | 0 | bag4contents | 24
```

That's before the update:
```

player | inv_id | inv_width | inv_name | inv_size
-- | -- | -- | -- | --
User123 | 0 | 0 | main | 32
User123 | 1 | 0 | craft | 9
User123 | 2 | 0 | craftpreview | 1
User123 | 3 | 0 | craftresult | 1
User123 | 8 | 0 | bag1contents | 24
User123 | 9 | 0 | bag2contents | 24
User123 | 10 | 0 | bag3contents | 24
User123 | 11 | 0 | bag4contents | 24
```

So right after discovery I restored the backup, but some players had already logged in.

Those players that had not logged in, found their old bags on the restored unified_inventory unharmed.
Those few players that had logged in, couldn't find their bags again, independent of whether they added new bags to their then-empty inventory slots or not.

For my reference 310

**Comment by SmallJoker** [comment]
Since 2018 the bag contents and bags themselves are saved in the player metadata for safety reasons. This means `bag[1-4]` are saved in player metadata, and the actual contents are still kept in the player inventory data.

Converting old format to new:
https://github.com/minetest-mods/unified_inventory/blob/fbbf786caf056aff70eec25f0878925f89d49bbe/bags.lua#L141-L151

Creation of `bag[1-4]` slots:
https://github.com/minetest-mods/unified_inventory/blob/fbbf786caf056aff70eec25f0878925f89d49bbe/bags.lua#L152-L157

`bag[1-4]` are created temporary while the player is online. Would you mind looking up what's contained in the metadata?

**Comment by Bastrabun** [comment]
I have three points in time where I could look at the metadata.

a) Before I updated to the latest release of unified inventory
b) After I updated to the latest release
c) After I went back to the previous release

Also, there are players who logged in during b) and those who did not. Which combination do you want to see?

Current state of the server is c) and a player who had logged in while the latest release was active, has those in the meta, after I gave him 4 large bags and he applied them:

```
player | attr | value
-- | -- | --
  | unified_inventory:bags | return {"unified_inventory:bag_large", "unified_inventory:bag_large",  "unified_inventory:bag_large", "unified_inventory:bag_large"}
-- | -- | --
```

Before, this meta is missing. I can see it on a player who also logged in, but has not replaced the bags yet. The entry is not empty, it simply is not there.

We can recreate it on a testserver, where I restore the database from before the update, then update and you can tell me what to investigate.

**Comment by SmallJoker** [comment]
Which was your previous unified_inventory version? The more it can be narrowed down, the easier it is to troubleshoot.

The data of players who did not login use the old format (apparently pre-2018). No metadata, and bags in inventory slots.
Players who logged in using the newest version (`master`) will only have `bag?contents` slots, and the items previously in `bag?` will be present in the metadata.

> after I gave him 4 large bags and he applied them:

Does this data show the metadata before or after they re-added the bags to the inventory slots? Either way this value should be the same before and after.

Procedure for proper testing:

1. Check the contents of the backup without "bag loss" (inventory data only, metadata should not exist)
2. Update unified inventory to the current version
3. Add `minetest.log("none", "bag contents of "..player:get_player_name()..": "..dump(bags))` below the following line:
https://github.com/minetest-mods/unified_inventory/blob/fbbf786caf056aff70eec25f0878925f89d49bbe/bags.lua#L126
4. Join & leave with an account where the bags disappear
5. Check the logs, inventory data (`bag?` slots must be gone), metadata (`unified_inventory:bags` must exist)

**Comment by Bastrabun** [comment]
I uploaded both versions of unified_inventory here:

This is the version I upgraded from:

https://your-land.de/additional/unified_inventory_old.7z

This is the version I upgraded to:

https://your-land.de/additional/unified_inventory_new.7z

###

Check the contents of the backup without "bag loss" (inventory data only, metadata should not exist)

On the old version I made a test account. It has no mentions of bags in the metadata, but it has inventories. The username is "Previous" and he has a small bag in the first inventory slot:

player 	inv_id 	inv_width 	inv_name 	inv_size
Previous 	0 	0 	main 	32
Previous 	1 	3 	craft 	9
Previous 	2 	0 	craftpreview 	1
Previous 	3 	0 	craftresult 	1
Previous 	4 	0 	bag1 	1
Previous 	5 	0 	bag2 	1
Previous 	6 	0 	bag3 	1
Previous 	7 	0 	bag4 	1
Previous 	8 	0 	bag1contents 	8

After I inserted the minetest.log call in the line indicated, I restarted the server and logged in and out with the "Previous" account.

- There was no entry in the logfile
- The inventory data had vanished, the player_inventories looked like this:

player 	inv_id 	inv_width 	inv_name 	inv_size
Previous 	0 	0 	main 	32
Previous 	1 	3 	craft 	9
Previous 	2 	0 	craftpreview 	1
Previous 	3 	0 	craftresult 	1
Previous 	4 	0 	bag1contents 	8

- The metadata in player_metadata does not exist.

###

Does this data show the metadata before or after they re-added the bags to the inventory slots? Either way this value should be the same before and after.

> It shows the metadata after the bag was re-added to the inventory slot. Before, the metadata was not present, afterwards it was.

###

Looks like save_bags_metadata(player, bags_inv) does not get called during on_joinplayer. So I wanted to know what's in bags_meta and dirty_meta.

What's in bags_meta right before line 

141 if not bags_meta then

bags_meta=""

This causes the loop not executed and dirty_meta=false

bags_meta comes out of

meta:get_string("unified_inventory:bags")

Which eventually gets set in the (not called during on_joinplayer) function save_bags_metadata(player, bags_inv)

**Comment by SmallJoker** [comment]
https://github.com/minetest-mods/unified_inventory/blob/fbbf786caf056aff70eec25f0878925f89d49bbe/bags.lua#L138

Does it fix your issue by replacing `get_string` with `get` ?

**Comment by SmallJoker** [comment]
d1a4396fb

**Comment by Bastrabun** [comment]
Tested in my environment and it works. Thank you!
