### ISSUE TITLE
Unified Inventory just doesn't work. What am I missing?

### ISSUE THREAD

**Issue by IITFA** [minetest-mods/unified_inventory#176]
So I have went through and compiled a minetest server and client using the latest git and the server runs and the client runs and all the mods are working except Unified Inventory. I can't find anything obvious in the debug file,

EDIT: Ok, so, running a server via the GUI (opening minetest and start game) works, but running a server using minetestserver via console does not work.

**Comment by SmallJoker** [comment]
Is `unified_inventory` listed in `/mods`?
Which MInetest version is your client and server?
What's not working? Check whether the same happens (or does not happen) in a newly created world, without any supplementary mods.

**Comment by IITFA** [comment]
I found out that for some reason, 3d_armor was causing the issues. Removing 3d_armor fixed it.
