### ISSUE TITLE
Doesn't work on Mineclone2

### ISSUE THREAD

**Issue by TheFreePenguin** [minetest-mods/unified_inventory#177]
I try running this mod on mineclone2, it crashes

**Comment by SmallJoker** [comment]
HUD/awards optionally depends on `unified_inventory`
HUD/mcl_achievements depends on `HUD/awards`

.. but `unified_inventory` cannot be loaded because its `default` dependency is not fulfilled. 

This is a Minetest bug. https://github.com/minetest/minetest/issues/8601
