### ISSUE TITLE
Setting to hide items without crafting recipe

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/unified_inventory#178]
Can you please add a setting that hides items in the crafting guide, when they have no crafting recipe?

I believe I can remember a version where this was default, but sometime in between got changed

**Comment by SmallJoker** [comment]
Relevant code in case anyone would like to work on it.
https://github.com/minetest-mods/unified_inventory/blob/afd38e0c731eeaf53933c3039042b6eb1fcf899d/api.lua#L13-L43

**Comment by SmallJoker** [comment]
Added in #240
