### ISSUE TITLE
Buttons at bottom hidden by page navigation

### ISSUE THREAD

**Issue by AmyMoriyama** [minetest-mods/unified_inventory#193]
Buttons at bottom hidden by page navigation. How can this be fixed?

![unifiedinventory](https://user-images.githubusercontent.com/87048190/148022005-32cccf76-ac8e-40e6-9272-b8bd863ce33e.png)

**Comment by SmallJoker** [comment]
Either by removing stuff, adding a second column or moving everything into a scroll container. What would be preferred?

**Comment by AmyMoriyama** [comment]
Scroll container?

**Comment by SmallJoker** [comment]
Assuming you're asking what a scroll container is. It's comparable to an HTML iframe: A separate page which is embedded into the main inventory formspec. Or also similar to long text fields but with a horizontal scrollbar in this case, rather than vertical.

**Comment by AmyMoriyama** [comment]
Scroll container would probably work but a second row for overflow might look nicer.
