### ISSUE TITLE
Sweeping in item search is not reset if the search field is empty. 

### ISSUE THREAD

**Issue by nikolaus-albinger** [minetest-mods/unified_inventory#196]
Sweeping in item search does not reset if the search field is empty. Problem present since 23a45b8.

**Comment by SmallJoker** [comment]
Would you please be so nice to provide exact steps on how to reproduce this problem?

**Comment by nikolaus-albinger** [comment]
1. Open inventory and enter a search item or node
2. Confirm entry
3. Empty the search field by pressing the remove key on the keyboard
Now comes the problem:
If the search field is now empty, you can no longer reset the search by pressing the brush to come on page 1.

**Comment by nikolaus-albinger** [comment]
Small correction: If the search field is empty while the item list is still limited, it is not possible to leave it without entering the search field.

**Comment by SmallJoker** [comment]
Fixed in 25c40fe.
