### ISSUE TITLE
undo 64b0248

### ISSUE THREAD

**Issue by Niklp09** [minetest-mods/unified_inventory#202]
The tooltip always shows the mod in which the items were registered, the item string which can now only be seen, but often a different one. Therefore the mod name should be added back to the tooltip.
![grafik](https://user-images.githubusercontent.com/89982526/159128123-ee3354a7-536a-4c52-af91-02ff77e399f2.png)

Image: Item is registered using homedecor_gastronomy. But the item string is homedecor:...

**Comment by SmallJoker** [comment]
@JordanL2 The item name does not always correspond to the mod which registered it. I'd like to hear your opinion on this (due to #190).

**Comment by JordanL2** [comment]
I think it can be restored. The motivation for the removal was that if you register a node during the `register_on_mods_loaded` callback, the `mod_origin` doesn't get set. However, it is possible to forcibly override mod_origin, so this isn't the problem I originally thought it was.

So yes, I think this can be undone.

**Comment by SmallJoker** [comment]
d065e02. In case of `not mod_origin`, nothing is appended to keep the text nice-looking when this information is missing.
