### ISSUE TITLE
Craftguide bug since "5ac2558"

### ISSUE THREAD

**Issue by Niklp09** [minetest-mods/unified_inventory#204]
As of `5ac2558`, ingredient results are no longer displayed

`25c40fe` still works 

![grafik](https://user-images.githubusercontent.com/89982526/164774121-130db2cf-1b0e-410d-9054-8effd308c0ff.png)

Since `5ac2558` Doesn't work anymore

![grafik](https://user-images.githubusercontent.com/89982526/164774996-5561e075-44ab-4904-ac92-59be8f4e2ca2.png)

**Comment by debagos** [comment]
I can confirm this issue on the latest master.

**Comment by SmallJoker** [comment]
14da1a3

**Comment by debagos** [comment]
Thank you very much for the super fast fix @SmallJoker! :tada:
