### ISSUE TITLE
Proposal crafting

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest-mods/unified_inventory#206]
This style of crafting would be better
![ i](https://raw.githubusercontent.com/minetest-mods/simplecrafting_lib/master/screenshot.png)

Source of information https://github.com/minetest-mods/simplecrafting_lib

**Comment by SmallJoker** [comment]
This is indeed a much more straight-forward solution, but the adventure/learning approach of the traditional crafting grid would be completely lost.
:-1: I think Unified Inventory should not change in this regard.
