### ISSUE TITLE
Add setting type to disable categories

### ISSUE THREAD

**Issue by snowtest-sled** [minetest-mods/unified_inventory#210]
Please add an option to hide categories

**Comment by SmallJoker** [comment]
Why?

**Comment by v3nc** [comment]
I don't know someone wrote a review on ContentDB and said that they didn't like categories

**Comment by SmallJoker** [comment]
Not enough information what's exactly wanted. I can imagine the following:

 * Disable default categories to add custom ones from scratch
 * Hide the selector for more recipe guide space
 * Hide individual categories

Closing until someone can tell the request in detail.
