### ISSUE TITLE
Show technical names

### ISSUE THREAD

**Issue by mase76** [minetest-mods/unified_inventory#212]
Hi!
It would be nice, if the technical node names were also shown, when hovering over an item. There are some situations, where this names could be useful, also when the player uses an other language than english. For example, I have built an automated storage system, where the player can type an item and amount. Therefor the technical names are needed. At the moment, I only see the technical names in the crafting guide.

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/c607bee19e286165fd497d57d2bb2b8ac5986f36/minetest.conf.example#L538-L540

Minetest feature.
