### ISSUE TITLE
[Feature request] Option to show large item icon by mouse hovering

### ISSUE THREAD

**Issue by GrimPixel** [minetest-mods/unified_inventory#214]
Hi. I am creating a mod about tabletop games. Players need to see their magnified images. So I would like to see this feature for playing the games.

**Comment by GrimPixel** [comment]
I see the item name appears when I hover over it. So I guess there is an answer. About that client server delay, I think the images are already in the inventory, so they just need to be enlarged.
Anyway. I am working on another solution for playing tabletop games.

**Comment by SmallJoker** [comment]
Tooltips are a client-side feature and are not implemented by unified_inventory. unified_inventory can only send updated formspecs to the client when there's an event. Anything that's supposed to happen client-side is a task for the Minetest Engine itself.

**Comment by SmallJoker** [comment]
Cannot implement: lack of Minetest Engine features.
