### ISSUE TITLE
Possible to cause server lag or denial of service by spamming search requests

### ISSUE THREAD

**Issue by Montandalar** [minetest-mods/unified_inventory#215]
[L-Dog on Minetest forums](https://forum.minetest.net/viewtopic.php?p=416028#p416028) reports that it's possible to cause major disruptive lag simply by spamming searches. A per-player rate limit should probably be applied to `unified_inventory.apply_filter`, especially since that can iterate all of `minetest.registered_items`.

**Comment by fluxionary** [comment]
been somewhat aware of this issue for a while. a rate limiter would be welcome.

**Comment by SmallJoker** [comment]
https://github.com/minetest-mods/unified_inventory/blob/177debd13ce27db9538b35e2443ed233105b79d6/callbacks.lua#L75-L82


Duplicates are already ignored. Perhaps it would make sense to optimize `apply_filter` instead. I will have a look into that.

**Comment by Niklp09** [comment]
https://github.com/minetest-mods/unified_inventory/issues/192

**Comment by SmallJoker** [comment]
Whoever encounters this issue in the newest Unified Inventory version is kindly asked to provide reproduction steps. At best, also profile the mod to narrow down the callbacks/functions that take longest.

Closing until further information is provided.
