### ISSUE TITLE
unified inventory collapsing to standart version during usage

### ISSUE THREAD

**Issue by Festus1965** [minetest-mods/unified_inventory#216]
engine 5.5.0, game same i hope
ui and ui+ frrom 04.2022

happen now AFTER updated mod crafting from 2017 to 2021 version
BUT I have seem that problem earlier as also of try update crafting, and therefor stay at 2017 version
but now crafting crash ... update was needed

here how it happen : https://youtu.be/lOMvFsKSaeQ

any settings I miss ?

**Comment by fluxionary** [comment]
@Festus1965 any chance you can provide a list of other mods (and versions), and which version of unified_inventory that you're using?

**Comment by Festus1965** [comment]
unified_inventory : 
https://github.com/minetest-mods/unified_inventory
- new : 14da1a3/23.04.2022
- old : 04b2edc/06.06.2020

problem occurs with newer crafting !
I am back on old version - no problem

ui plus : 
ttps://github.com/bousket/unified_inventory_plus
same : 63b1490/17.04.2022

crafting : https://github.com/rubenwardy/crafting
- before : and no problem cf1ad1b/09.05.2017
- with problem every opening : 203ce5f/27.1.2021

**Comment by fluxionary** [comment]
> crafting : https://github.com/rubenwardy/crafting

i'm guessing the conflict is w/ the crafting mod, i'll test this and report back. crafting is aware of sfinv, but not unified_inventory (or i3, or other inventory managers). probably, the solution should be part of that mod. imo, this should ultimately be handled w/ a lower-level API mod that helps other mods create the inventory formspec without stepping on each-other's toes, but that doesn't exist currently.

as an aside, if you're using a mod that's supposed to remove the crafting grid, why would you expect to be able to use the crafting grid?

**Comment by fluxionary** [comment]
I can't replicate this w/ just crafting unified_inventory, and unified_inventory_plus (and minetest game). seems this is on the Asia Thailand server? the full mod list is huge, and i'll try to audit it:
```
3d_armor, 3d_armor_ip, 3d_armor_sfinv, 3d_armor_stand, 3d_armor_ui, alphabet, animal_resources, animalmaterials, anvil, areas, arrow_signs, atm, bakedclay, baldcypress, bamboo, baobab, basic_materials, basic_robot, basic_signs, beacon, beds, beerchat, beowulf, binoculars, biofuel, biome_lib, birch, boats, bonemeal, bones, border, bows, bucket, building_blocks, bushes, bushes_classic, butterflies, cacaotree, carts, cavestuff, cherrytree, chestnuttree, clementinetree, computer, cooking, crafting, creative, currency, default, digilines, digtron, display_api, doors, dryplants, dungeon_loot, dye, ebony, env_sounds, ethereal, euban, fancy_vend, farming, farming_nextgen, ferns, fire, fireflies, flowerpot, flowers, flowers_plus, game_commands, geocache, give_initial_stuff, hangglider, hec_diamaster, hec_honeypot, hec_nether, hec_nodemani, hec_nopvp, hec_obsidian_stuff, hec_vicount, hidden_doors, hollytree, homedecor_3d_extras, homedecor_bathroom, homedecor_bedroom, homedecor_books, homedecor_climate_control, homedecor_clocks, homedecor_cobweb, homedecor_common, homedecor_doors_and_gates, homedecor_electrical, homedecor_electronics, homedecor_exterior, homedecor_foyer, homedecor_furniture, homedecor_furniture_medieval, homedecor_gastronomy, homedecor_kitchen, homedecor_laundry, homedecor_lighting, homedecor_misc, homedecor_office, homedecor_pictures_and_paintings, homedecor_roofing, homedecor_seating, homedecor_tables, homedecor_trash_cans, homedecor_wardrobe, homedecor_windows_and_treatments, hud, hunger, hyperloop, inbox, intllib, inventorybags, itemframes, jacaranda, jumpdrive, junglegrass, keys, lamps, larch, lavalamp, lavastuff, lcdlib, lemontree, locks, mahogany, mail, map, maple, markers, mesecons, mesecons_alias, mesecons_blinkyplant, mesecons_button, mesecons_delayer, mesecons_detector, mesecons_doors, mesecons_extrawires, mesecons_fpga, mesecons_gamecompat, mesecons_gates, mesecons_hydroturbine, mesecons_insulated, mesecons_lamp, mesecons_lightstone, mesecons_luacontroller, mesecons_materials, mesecons_microcontroller, mesecons_movestones, mesecons_mvps, mesecons_noteblock, mesecons_pistons, mesecons_powerplant, mesecons_pressureplates, mesecons_random, mesecons_receiver, mesecons_solarpanel, mesecons_stickyblocks, mesecons_switch, mesecons_torch, mesecons_walllever, mesecons_wires, minecart, minetest_remover, mobs, mobs_animal, mobs_bat, mobs_birds, mobs_butterfly, mobs_fish, mobs_humans, mobs_jellyfish, mobs_npc, moderator_armor, molehills, more_chests, moreblocks, moremesecons_adjustable_blinkyplant, moremesecons_adjustable_player_detector, moremesecons_conductor_signalchanger, moremesecons_dual_delayer, moremesecons_entity_detector, moremesecons_igniter, moremesecons_induction_transmitter, moremesecons_injector_controller, moremesecons_mesechest, moremesecons_playerkiller, moremesecons_sayer, moremesecons_signalchanger, moremesecons_switchtorch, moremesecons_teleporter, moremesecons_timegate, moremesecons_utils, moremesecons_wireless, moreores, moretrees, mtg_craftguide, names_per_ip, nature_classic, nether, networks, nixie_tubes, node_changer, nyancat, oak, palm, pineapple, pipeworks, plantlife_i18n, plasmascreen, player_api, plumtree, poisonivy, pomegranate, protector, qos, safer_lua, scifi_nodes, screwdriver, sequoia, server_news, serveressentials, sethome, sfinv, shields, sightview, signs_lib, smartshop, spacesuit, spawn, spawn_command, spectator_mode, srvstuff, stairs, stats, techage, tnt, toolranks, torches, trash_can, travelnet, trunks, tubelib2, u_skins, unified_inventory, unified_inventory_plus, unifieddyes, vessels, walls, weather, wieldview, wiki, willow, woodcutting, woodsoils, wool, xdecor, xp_redo, xp_redo_ranks_ores, xpanes, xtraores, xtraores_armor, youngtrees
```

**Comment by fluxionary** [comment]
after poking at this a little more, i'm convinced that "crafting" and unified_inventory are fully irreconcilable w/ currently available APIs, in the same way that unified_inventory and i3 are. they're both trying to fully manage the same thing.

**Comment by Festus1965** [comment]
yes,
AsiaThailand

and just this two new gamer found that bug in crafting ... pointing out the problem

Ok
so next crash restart without crafting anyway and see
as you point me to this fact : both are similar mod, only one is needed

Thanks

**Comment by Festus1965** [comment]
should be solved
mod crafting is deactivated to next restart
