### ISSUE TITLE
recipes using groups with no match show the group as an unknown item

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/unified_inventory#218]
~~it is possible to specify that an item in a recipe must belong to multiple groups simultaneously:~~

~~https://github.com/minetest/minetest/blob/1a045da0dd7f086a6ca689620aeb0fa28a1f6ce6/doc/lua_api.txt#L1847-L1853~~

~~unified inventory handles the case properly when the intersection matches one or more items. however, if the intersection matches nothing, it will still display the recipe, but indicate that the recipe contains an unknown item.~~

edit: it seems this applies to single groups too, not just group intersections.

to test:

* use minetest_game
* create a dummy mod w/ the following in init.lua

```lua
minetest.clear_craft({output = "default:stone"})
minetest.register_craft({
 output = "default:stone",
 recipe = {{"group:blahblah"}},
})
```

mod.conf:
```
name = badrecipe
depends = default
```

results:
![screenshot_20221114_092921](https://user-images.githubusercontent.com/25628292/201726585-2c864f3b-436c-4945-a4e2-8d91e8c3f63e.png)

expected behavior: the recipe for "stone" shouldn't show up

**Comment by fluxionary** [comment]
updated the description as it appears to affect simple group matches too, not just intersections.

**Comment by SmallJoker** [comment]
#223
