### ISSUE TITLE
craftguide "craft" buttons don't work w/ recipes w/ items specified by multiple groups.

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/unified_inventory#222]
example recipe:

```lua
minetest.register_craft({
    output = "cucina_vegana:imitation_poultry",
    recipe = {
        {"group:food_tofu_raw", "", "group:dye,color_yellow"},
        {"", "group:food_tofu_raw", ""},
        {"group:food_tofu_raw", "group:food_tofu_raw", "group:food_tofu_raw"}
    }
})
```

get some stuff in your inventory, and click "all"
![image](https://user-images.githubusercontent.com/25628292/210460282-addd6b8d-6e99-4e36-a4b0-f1cdb6aa4821.png)

result: nothing:
![image](https://user-images.githubusercontent.com/25628292/210460360-afaa46a4-6f2b-4c86-8d0b-6e750deeea3c.png)

**Comment by SmallJoker** [comment]
https://github.com/minetest-mods/unified_inventory/blob/82cdf24045ecb6821876e77b6d3e42aec590c9c9/match_craft.lua#L128-L152

does yet not handle multiple groups, hence there's no matching items in the inventory. I'll have a look at this.
