### ISSUE TITLE
waypoints should have a teleport to this coordinate button

### ISSUE THREAD

**Issue by imre84** [minetest-mods/unified_inventory#230]
Hello,

in case the current player has teleport privileges the waypoints tab should have a teleport to this coordinate button

thank you in advance, and have a great day

**Comment by SmallJoker** [comment]
Adding a new table entry here for players with the "teleport" priv would be trivial:
https://github.com/minetest-mods/unified_inventory/blob/b2cc3d15320aabc9df0d6d90e22e7661099dbb8a/waypoints.lua#L141-L148

And then handling the button press here:
https://github.com/minetest-mods/unified_inventory/blob/b2cc3d15320aabc9df0d6d90e22e7661099dbb8a/waypoints.lua#L307-L314

I could implement that if you happen to have a good and free icon that also allows commercial use (e.g. CC-BY-SA or CC-BY).

**Comment by imre84** [comment]
a quick duckduckgo search (free svg teleport) gives these results:

https://freesvg.org/teleport-person
https://www.flaticon.com/free-icon/teleport_1636861
https://www.svgrepo.com/svg/499335/player-teleport
https://www.svgrepo.com/svg/321565/teleport

are these good?

**Comment by SmallJoker** [comment]
https://www.svgrepo.com/svg/321565/teleport seemed to fit the best for the style of Unified Inventory (after colorizing)

Implemented as of 15d729c.
