### ISSUE TITLE
Armor inventory position is offset

### ISSUE THREAD

**Issue by za267** [minetest-mods/unified_inventory#238]
The appearance of items in the armor inventory appear to be misplaced/out of position compared to the boxes.

![screenshot_20231223_121314](https://github.com/minetest-mods/unified_inventory/assets/2365202/9f254df9-3516-430c-b395-bc84988ff3bd)

**Comment by SmallJoker** [comment]
This tab is added by the mod `3d_armor_ui`. Please make sure that you are using the newest 3d_armor version from https://github.com/minetest-mods/3d_armor .

**Comment by za267** [comment]
I see, thank you- I will try that.
