### ISSUE TITLE
When clicking on tab with iron lump icon game exits to main menu

### ISSUE THREAD

**Issue by Alatarius** [minetest-mods/unified_inventory#243]
Just as the title says but it exits with this error.

```
AsyncErr: Lua: Runtime error from mod 'unified_inventory' in callback on_playerReceiveFields(): ...ames\Minetest\bin\..\mods\unified_inventory/internal.lua:386: bad argument #1 to 'lower' (string expected, got table)
stack traceback:
	[C]: in function 'lower'
	...ames\Minetest\bin\..\mods\unified_inventory/internal.lua:386: in function 'ffilter'
	...ames\Minetest\bin\..\mods\unified_inventory/internal.lua:417: in function 'apply_filter'
	...mes\Minetest\bin\..\mods\unified_inventory/callbacks.lua:114: in function <...mes\Minetest\bin\..\mods\unified_inventory/callbacks.lua:91>
	D:\Games\Minetest\bin\..\builtin\common\register.lua:26: in function <D:\Games\Minetest\bin\..\builtin\common\register.lua:12>
```

[edit] forgot to add that this started happening after technic_mod updated

**Comment by SmallJoker** [comment]
@Alatarius Unfortunately I cannot reproduce this with Minetest Game + Unified Inventory enabled. Which additional mod triggers this error?

**Comment by Alatarius** [comment]
> @Alatarius Unfortunately I cannot reproduce this with Minetest Game + Unified Inventory enabled. Which additional mod triggers this error?

This started happening after I updated the technic mod

**Comment by SmallJoker** [comment]
@Alatarius Unfortunately your problem description is similar to "help, my printer does not work". I cannot reproduce this on my end (Minetest 5.9.0-dev, newest Minetest Game), thus please reproduce the error in a new world, starting with only Unified Inventory. Enable mods one by one to figure out which one introduces it.

I could fix the error in a hacky way but I prefer proper solutions, thus this request.

**Comment by Alatarius** [comment]
When I selected each mod individually they all worked. Then I tried activating them 1 at a time so they were all active and that worked. Then I used the "/grantme all" command and then it crashed again with the above error

**Comment by Alatarius** [comment]
These are the mods that I currently have active:

3d_apple, 3d_armor, airtanks, airutils, ambience, amethyst_new, animalworld, anvil, area_containers, artdeco, auroras, awards, bakedclay, banner, basic_materials, beds, biofuel, biomeinfo, biome_lib, bonemeal, bows, bricks_plus, bucket, bucket_wooden, builtin_item, carpets, castle_farming, castle_gates, castle_lighting, castle_masonry, castle_shields, castle_storage, castle_tapestries, castle_weapons, connected_chests, controls, cottages, cracked_castle, craftguide, darkage, decorations_sea, deepslate, digicontrol, digilines, digistuff, digtron, display_modpack, doc, doc_basics, doc_encyclopedia, doc_identifier, doc_items, doors, drinks, elevators, ethereal, etherium_stuff, everness, extended_placement, facade, factory, factory_bridges, farming, fireworkz, flowerbeds, flowerpot, furniture, geodes_lib, glass_stained, handle_schematics, hangglider, hopper, hopper_compat, illumination, itemframes, item_drop, leads, leather_armor, livingcaves, livingcavesmobs, livingdesert, livingfloatlands, livingjungle, livingnether, loot, lwcomponents, lwscratch, marinara, marinaramobs, mesebox, mesecons, mesecons_window, mesecons_x, meseportals, microexpansion, micupack, minecart, minimap_radar, mobkit, mobs, mobs_animal, mobs_monster, mobs_skeletons, mobs_sky, mobs_water, modlib, modname_tooltip, modutil, moreblocks, moredecorations, morelights, morelights_dim, moremesecons, moreores, moretorches, moretrees, music_modpack, nativevillages, naturalbiomes, nether, new_campfire, obsidianstuff, omnidriver, paintings_gallery, paintings_lib, pipeworks, plaster, powerbanks, redef, regrowing_fruits, research and, development, ropes, scaffolding, servercleaner, shallow_ores, signs_lib, simple_furniture, skinsdb, slats, stackslabs, stainedglass, stamina, stripped_tree, sugar, swamp, technic_plus, technic_recipes, techpack, tga_encoder, torch_bomb, tpad, ts_furniture, tt, tubelib2, unifieddyes, unified_inventory, variety, visible_sneak, void_chest, wilhelminessounds, wine, woodcutting, xdecor, xmaps, x_enchanting, x_farming

**Comment by Alatarius** [comment]
I now tried uninstalling the mod that I added when it crashed and even then I still get the same error as above. Then I disabled every mod except UI and I still got the same error as above. It only seems to work on a brand new game and then after it crashes the same error exists for me even after disabling every mod including UI.

**Comment by Alatarius** [comment]
The best I could come up with is any of the Wilhelmines mods  will crash mt_game with UI active. It also crashed when I enabled music or new sounds to the game.

**Comment by ryleestatler** [comment]
same issue, started happening after updating the mod

AsyncErr: Lua: Runtime error from mod 'unified_inventory' in callback on_playerReceiveFields(): ...t-5.8.0-win64\bin\..\mods\unified_inventory/internal.lua:386: bad argument #1 to 'lower' (string expected, got table)
stack traceback:
	[C]: in function 'lower'
	...t-5.8.0-win64\bin\..\mods\unified_inventory/internal.lua:386: in function 'ffilter'
	...t-5.8.0-win64\bin\..\mods\unified_inventory/internal.lua:417: in function 'apply_filter'
	...-5.8.0-win64\bin\..\mods\unified_inventory/callbacks.lua:114: in function <...-5.8.0-win64\bin\..\mods\unified_inventory/callbacks.lua:91>
	...ta\minetest-5.8.0-win64\bin\..\builtin\game\register.lua:446: in function <...ta\minetest-5.8.0-win64\bin\..\builtin\game\register.lua:432>

**Comment by SmallJoker** [comment]
Could someone who's affected by this issue please apply the following diff and check the chat output?
```diff
diff --git a/internal.lua b/internal.lua
index daa3ba1..19d32cf 100644
--- a/internal.lua
+++ b/internal.lua
@@ -382,6 +382,10 @@ function ui.apply_filter(player, filter, search_dir)
                local lang = player_info and player_info.lang_code or ""
 
                ffilter = function(name)
+                       if type(name) == "table" then
+                               minetest.chat_send_all("Unified Inventory: " .. dump(name))
+                               return false
+                       end
                        local def = registered_items[name]
                        local lname = string.lower(name)
                        local ldesc = string.lower(def.description)
```

**Comment by SmallJoker** [comment]
(removed my previous answer: obsolete)

Since commit 004a39a all node drops are now handled properly and invalid registrations are logged as warning. This will ease debugging in the future in case of unexpected (or faulty?) item or node registrations.
Please report back whether this resolved your issue and any new log entries.

**Comment by Alatarius** [comment]
UI mostly works now except that the bags no longer are able to be put in the bag slots.
