### ISSUE TITLE
Crafting recipes for items hidden from creative inventory are not visible in crafting guide

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/unified_inventory#66]
The mod is missing the following crafting recipes of Minetest Game:
- Book + Book with Text → Book with Text
- Digging: Wheat Plant (full size) → Wheat
- Digging: Wheat Plant (full size) → Wheat seed
- Digging: Cotton Plant (full size) → Cotton
- Digging: Cotton Plant (full size) → Cotton seed

What have all sources in common? They are hidden from creative inventory.
Note the reason why the last 4 are not displayed is not solely because complex drops (table-based) are not yet supported. I have implemented this in a PR and those drops still don't appear in the crafting guide.

When I add any of the special items (Book with Text, wheat plant, cotton plant) to the creative inventory and set their `description`, the crafts become visible again.

IMO the design flaw here is that items not in creative inventory are assumed to have no crafts in either direction. This assumption is false. If `not_in_creative_inventory` is set, it does not automatically mean there are no crafts involved with this item.

The tricky question is how can be add such crafting recipes without actually adding the items to the creative inventory?

**Comment by VanessaE** [comment]
Generally, I guess `not_in_creative_inventory` is taken by most modders to mean "shouldn't be obtainable by the user at all".  I'd have to assume (without digging through the commit history) that it's intentional that UI makes the same assumption.

**Comment by Wuzzy2** [comment]
While the 4 digging “recipes” are more esoterical cases and it is maybe a “lesser sin” to not have them visible, the book with text recipe is a real crafting recipe with an actual use, so it clearly should be visible. The book with text is also easily obtainable by writing something into a book, so even for Minetest Game, the assumption that `not_in_creative_inventory` also means “completely unobtainable” is totally false.
It is not uncommon for items to have the group `not_in_creative_inventory` yet it is perfectly fine for the player to have it. I also want to remind you of the mod `unifieddyes`. ;-)

Besides, I think it is a mistake to try to interpret things into groups for which they were never intended.
`not_in_creative_inventory` just means that: It's not in the creative inventory.

**Comment by numberZero** [comment]
> The tricky question is how can be add such crafting recipes without actually adding the items to the creative inventory?

Well, there is a simple solution (that is entirely reasonable as long as `not_in_creative_inventory` is meant to reduce clutter only): a checkbox “Show items hidden by default.”

Actually, that may even be some other control to choose a maximum level of `not_in_creative_inventory` of items to show. This way, some exotic things like flowing lava might be given a high level, while e.g. stairs would remain at 1.

Moreover, that may be a solution for just another problem: there are often too many (17 IIRC) recipes when `moreblocks` are in effect, they’re really annoying when they come *before* normal recipes. (Note that I use the craft guide not only to find a recipe but also to fill my craft grid quickly, that’s when `moreblocks` just stand in the way)

**Comment by Wuzzy2** [comment]
No, numberZero, this is not a good solution. `not_in_creative_inventory` is also frequently used for items which are only used internally, like the strange “Hidden Door Section” (`doors:hidden`) in Minetest Game's `doors` mod.

**Comment by numberZero** [comment]
well, I simply forgot that the creative inventory is not only used by admins, but by normal players too, on *creative* servers... so there should be things not available for them. Anyway, my suggestion of assigning different levels would work here, would only it be used, which is not the case now.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/unified_inventory/issues
