### ISSUE TITLE
Ghost bags. Or: UI allows items to be placed into bag inventories without bag

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/unified_inventory#72]
UI has a rather funny bug ragarding bags:
- Place bag into bag slot 1
- Take bag from bag slot and click on the button for bag 1
- Place the bag into the bag inventory

You can now place anything you want into the inventory slots although the bag slot is empty.
You can return to the main bag screen to confirm it.
The bag button won't work this time, but you could place another bag into the slot in order to access the contents.

**Comment by VanessaE** [comment]
To clarify the issue, you have to click the button while the bag is still attached to the pointer.

I'm not sure if this can actually be fixed.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/unified_inventory/issues
